- id: arrive_home_after_sunset
  alias: Arriving Home After Sunset
  trigger:
  - platform: state
    entity_id: device_tracker.mitchs_iphone
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.renees_iphone
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.living_room_light_switch

- id: arrive_home
  alias: Arriving Home
  trigger:
  - platform: state
    entity_id: device_tracker.mitchs_iphone
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.renees_iphone
    from: 'not_home'
    to: 'home'
  action:
  - service: climate.ecobee_resume_program
    data:
      entity_id: climate.home
      resume_all: true

- id: hydroponic_fan_on
  alias: Hydroponic Fan On
  trigger:
  - platform: template
    value_template: "{{ states.sensor.hydroponics_state_temperature.state | int > 84 }}"
  action:
  - service: switch.turn_on
    entity_id: switch.hydroponics_control_switch_3

- id: hydroponic_fan_off
  alias: Hydroponic Fan Off
  trigger:
  - platform: template
    value_template: "{{ states.sensor.hydroponics_state_temperature.state | int < 78 }}"
  action:
  - service: switch.turn_off
    entity_id: switch.hydroponics_control_switch_3

- id: hydroponic_light_on
  alias: Hydroponic Light On
  trigger:
  - platform: time
    at: '2:00:00'
  - platform: time
    at: '19:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.hydroponics_control_switch_2

- id: hydroponic_light_off
  alias: Hydroponic Light Off
  trigger:
  - platform: time
    at: '1:30:00'
  - platform: time
    at: '8:30:00'
  action:
  - service: switch.turn_off
    entity_id: switch.hydroponics_control_switch_2

- id: login_failure
  alias: Login Failure
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
  action:
    service: script.ifttt_notify
    data_template:
      value1: 'Bad Login: '
      value2: 'There was a Hack attempt!'
      value3: 'Go Check the GUI for details.'

- id: leave_home
  alias: Leaving Home
  trigger:
  - platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  action:
  - service: homeassistant.turn_off
    entity_id: group.home
  - service: switch.turn_off
    entity_id: switch.coffee_switch
  - service: homeassistant.turn_off
    entity_id: script.coffee_timer_off
  - service: climate.set_away_mode
    data:
      entity_id: climate.home
      away_mode: true

- id: ha_update
  alias: Home Assistant Update
  trigger:
  - platform: state
    entity_id: updater.updater
  condition:
  - condition: template
    value_template: "{{ states('updater.updater') != 'unknown' }}"
  action:
  - service: notify.ios_mitchs_iphone
    data:
      title: 'New Version of Home-Assistant Available.'
      message: "Version: {{ states('updater.updater') }}"

- id: startup
  alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.html5
    data:
      title: 'Home Assistant'
      message: 'Up and Running!'
  - delay: 00:01:00
  - service: notify.ios_mitchs_iphone
    data:
      message: 'request_location_update'
  - service: notify.ios_renees_iphone
    data:
      message: 'request_location_update'

- id: sunrise
  alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:20:00"
  action:
  - service: switch.turn_off
    entity_id: switch.outside_light_switch

- id: sunset_when_home
  alias: Sunset When Home
  trigger:
    platform: sun
    event: sunset
    offset: "-00:10:00"
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.mitchs_iphone
      state: 'home'
    - condition: state
      entity_id: device_tracker.renees_iphone
      state: 'home'
  action:
  - service: switch.turn_on
    entity_id: switch.living_room_light_switch

- id: sunset
  alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.outside_light_switch

- id: turn_off_coffee
  alias: Trigger 2 hour coffee timer
  trigger:
    platform: state
    entity_id: switch.coffee_switch
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_coffee

- id: trigger_garage_timer_after_sunset
  alias: Trigger open garage door after sunset
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage_door_after_sunset

- id: trigger_garage_timer_after_sunrise
  alias: Trigger open garage door after sunset
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  condition:
  - condition: sun
    after: sunrise
    before: sunset
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage_door_after_sunrise

- id: notify_garage_open
  alias: Notify if garage open and empty house
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.mitchs_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.renees_iphone
      state: 'not_home'
  action:
  - service: notify.ios_mitchs_iphone
    data:
      message: 'Garage open after sunset... closing now.'
  - service: notify.ios_renees_iphone
    data:
      message: 'Garage open after sunset... closing now.'


