############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Pigsley Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 362
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

sun:
  elevation: 362

frontend:

updater:
  include_used_components: true

discovery:

logbook:

history:
  exclude:
    domains:
      - automation
      - sensor
      - updater
      - persistent_notification

recorder:
  purge_days: 7
  db_url: !secret recorder_db_url

############################################################
#
# Components
#
############################################################

emulated_hue:
  host_ip: 192.168.0.105
  listen_port: 8300
  off_maps_to_on_domains:
  exposed_domains:
    - script
    - switch
    - light
    - group
    - input_boolean
    - media_player

ios:

ecobee:

media_player:
  - platform: apple_tv
    name: bedroom_apple_tv
    host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
  - platform: sonos

sensor:
- platform: yr
- platform: darksky
  api_key: !secret darksky_api
  units: us
  monitored_conditions:
  - summary
  - precip_type
  - precip_intensity
  - precip_probability
  - temperature
  - wind_speed
  - humidity
  - pressure
  - visibility
  - temperature_max
  - temperature_min

light:
- platform: hue
  host: 192.168.0.110
  allow_unreachable: true

zwave:
  usb_path: /dev/ttyACM1
  new_entity_ids: true

############################################################
#
# Zones
#
############################################################
zone 1:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

zone 2:
  name: Mitch's Work
  latitude: !secret mitch_work_latitude
  longitude: !secret mitch_work_longitude
  radius: 500
  icon: mdi:briefcase

zone 3:
  name: Renee's Clinic
  latitude: !secret renee_clinic_latitude
  longitude: !secret renee_clinic_longitude
  radius: 500
  icon: mdi:hospital-building

zone 4:
  name: Renee's Private Practice
  latitude: !secret renee_private_practice_latitude
  longitude: !secret renee_private_practice_longitude
  radius: 500
  icon: mdi:home-variant
  

############################################################
#
# Includes
#
############################################################

# Single Files
group: !include includes/groups.yaml
notify: !include includes/notify.yaml
automation: !include includes/automation.yaml

# Merge Named
script: !include_dir_merge_named scripts
