homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 362
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:

http:
  api_password: !secret http_password

updater:

discovery:

conversation:

history:

logbook:

sun:

emulated_hue:
  host_ip: 192.168.0.105
  listen_port: 8300

sensor:
- platform: yr
- platform: forecast
  api_key: !secret forecast_key
  units: us
  monitored_conditions:
  - summary
  - precip_type
  - precip_intensity
  - precip_probability
  - temperature
  - wind_speed
  - humidity
  - pressure
  - visibility
  - temperature_max
  - temperature_min

light:
- platform: hue
  host: 192.168.0.100
  allow_unreachable: true

device_tracker:
- platform: tplink
  host: 192.168.0.1
  username: !secret router_username
  password: !secret router_password
  track_new_devices: no
  consider_home: 30
- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret
  username: !secret automatic_username
  password: !secret automatic_password

notify:
- platform: smtp
  name: Mitchel's Email
  server: smtp.gmail.com
  port: 587
  sender: !secret mitchel_email
  username: !secret mitchel_email
  password: !secret mitchel_email_password
  recipient: !secret mitchel_email
  starttls: true

group: !include groups.yaml

automation: !include_dir_list automation
