############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Pigsley Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 362
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include includes/customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

sun:
  elevation: 362

frontend:
  javascript_version: latest
  themes:
    dark:
      primary-color: "#233142"

updater:
  include_used_components: true

discovery:

logbook:

config:

history:
  exclude:
    domains:
    - automation
    - sensor
    - updater
    - persistent_notification

recorder:
  db_url: !secret recorder_db_url

############################################################
#
# Components
#
############################################################

emulated_hue:
  host_ip: 192.168.0.105
  listen_port: 8300
  off_maps_to_on_domains:
  exposed_domains:
  - script
  - switch
  - light
  - group
  - input_boolean
  - media_player

ios:

ecobee:

cover:
- platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: chamberlain

sensor:
- platform: yr
- platform: darksky
  api_key: !secret darksky_api
  units: us
  forecast:
  - 0
  monitored_conditions:
  - summary
  - temperature
  - humidity
  - visibility
  - temperature_high
  - temperature_low

light:
- platform: hue
  host: 192.168.0.110
  allow_unreachable: true
- platform: group
  name: Kitchen Sink
  entities:
  - light.kitchen_sink_1
  - light.kitchen_sink_2
  - light.kitchen_sink_3
- platform: group
  name: Living Room Side Tables
  entities:
  - light.living_room_side_table_left
  - light.living_room_side_table_right

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000
  device_config: !include includes/zwave_device_config.yaml

############################################################
#
# Zones
#
############################################################
zone 1:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

zone 2:
  name: LifeLoop
  latitude: !secret mitch_work_latitude
  longitude: !secret mitch_work_longitude
  radius: 500
  icon: mdi:briefcase

zone 3:
  name: Renee's Private Practice
  latitude: !secret renee_private_practice_latitude
  longitude: !secret renee_private_practice_longitude
  radius: 500
  icon: mdi:home-variant
  

############################################################
#
# Includes
#
############################################################

# Single Files
group: !include includes/groups.yaml
notify: !include includes/notify.yaml
automation: !include automations.yaml

# Merge Named
script: !include scripts.yaml
