# Tabs
default_view:
  name: Home
  view: yes
  entities:
  - group.family
  - group.forecast
  - group.automation

rooms:
  name: Rooms
  view: yes
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom

# Rooms
living_room:
  name: Living Room
  entities:
  - light.living_room_ceiling_fan_1
  - light.living_room_ceiling_fan_2
  - light.living_room_ceiling_fan_3

kitchen:
  name: Kitchen
  entities:
  - media_player.kitchen

master_bedroom:
  name: Master Bedroom
  entities:
  - switch.master_bedroom_light_switch_2

# Other
family:
  name: Family
  entities:
  - device_tracker.mitchel
  - device_tracker.renee

forecast:
  name: Forecast
  entities:
  - sun.sun
  - sensor.forecastio_summary
  - sensor.forecastio_temperature
  - sensor.forecastio_daily_high_temperature
  - sensor.forecastio_daily_low_temperature
  - sensor.forecastio_precip

automation:
  name: Automation
  entities:
  - automation.arriving_home_after_sunset
  - automation.home_assistant_update
  - automation.leaving_home
  - automation.sunset
