# Tabs
default_view:
  name: Home
  view: yes
  entities:
  - configurator.philips_hue
  - group.family
  - group.forecast
  - group.automation

rooms:
  name: Rooms
  view: yes
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.outside

# Rooms
home:
  name: Home
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom

living_room:
  name: Living Room
  entities:
  - light.living_room_ceiling_fan_1
  - light.living_room_ceiling_fan_2
  - light.living_room_ceiling_fan_3

kitchen:
  name: Kitchen
  entities:
  - media_player.kitchen
  - switch.kitchen_light_switch_switch_3_0
  - switch.coffee_switch_4_0

master_bedroom:
  name: Master Bedroom
  entities:
  - switch.master_bedroom_light_switch_switch_2_0
  - light.master_bedroom_reading

outside:
  name: Outside
  entities:
  - switch.outside_light_switch_switch_5_0

# Other
family:
  name: Family
  entities:
  - device_tracker.mitchel
  - device_tracker.renee

forecast:
  name: Forecast
  entities:
  - sun.sun
  - sensor.dark_sky_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_daily_high_temperature
  - sensor.dark_sky_daily_low_temperature
  - sensor.dark_sky_precip

automation:
  name: Automation
  entities:
  - automation.arriving_home_after_sunset
  - automation.home_assistant_update
  - automation.leaving_home
  - automation.sunset_when_home
  - automation.sunset
  - automation.sunrise
