
title: Pigsley Home
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Family
            show_header_toggle: false
            entities:
              - device_tracker.mitchs_iphone
              - device_tracker.renees_iphone
          - type: map
            entities:
              - device_tracker.mitchs_iphone
              - device_tracker.renees_iphone
      - type: history-graph
        title: Climate
        entities:
          - sensor.downstairs_temperature
          - sensor.home_temperature
          - sensor.dark_sky_temperature
          - sensor.hydroponics_state_temperature
      - type: thermostat
        entity: climate.home
      - type: entities
        title: Forecast
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.dark_sky_visibility
      - type: entities
        title: Hydroponics
        entities:
          - switch.hydroponics_control_switch
          - switch.hydroponics_control_switch_2
          - switch.hydroponics_control_switch_3
          - sensor.hydroponics_state_temperature
          - sensor.hydroponics_state_relative_humidity
          - sensor.hydroponics_state_luminance
          - sensor.hydroponics_state_ultraviolet
  - title: Rooms
    cards:
      - type: entities
        title: Master Bedroom
        entities:
          - switch.master_bedroom_light_switch
          - light.master_bedroom_reading
      - type: entities
        title: Mitchel's Office
        entities:
          - light.mitchels_office_reading
      - type: entities
        title: Exterior
        entities:
          - switch.outside_light_switch
      - type: vertical-stack
        cards:
          - type: entities
            title: Kitchen
            entities:
              - switch.kitchen_light_switch
              - switch.coffee_switch
              - light.kitchen_sink
          - type: media-control
            entity: media_player.kitchen
      - type: vertical-stack
        cards:
          - type: entities
            title: Basement
            entities:
              - light.basement_light_level
          - type: media-control
            entity: media_player.basement
          - type: media-control
            entity: media_player.basement_display
      - type: entities
        title: Garage
        entities:
          - cover.garage_door
      - type: entities
        title: Living Room
        entities:
          - light.living_room_side_tables
          - switch.living_room_light_switch
  - title: Automation
    cards:
      - type: entities
        title: All Automations
        entities:
          - automation.arriving_home
          - automation.sunset
          - automation.hydroponic_light_on
          - automation.arriving_home_after_sunset
          - automation.notifiy_close_garage_door_if_open_at_night
          - automation.trigger_2_hour_coffee_timer
          - automation.hydroponic_light_off
          - automation.hydroponic_fan_off
          - automation.home_assistant_update
          - automation.leaving_home
          - automation.sunrise
          - automation.startup_notification
          - automation.hydroponic_fan_on
          - automation.mitchel_s_morning_reading
      - type: entities
        title: All Scripts
        entities:
          - script.thermostat

