
title: Pigsley Home
views:
  - title: Home
    cards:
      - type: entities
        title: Family
        show_header_toggle: false
        entities:
          - device_tracker.mitchs_iphone
          - device_tracker.renees_iphone
      - type: entities
        title: Climate
        show_header_toggle: false
        entities:
          - sensor.master_bedroom_temperature
          - climate.home
          - sensor.home_temperature
      - type: entities
        title: Forecast
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.dark_sky_visibility
      - type: entities
        title: Hydroponics
        entities:
          - sensor.hydroponics_state_luminance
          - switch.hydroponics_control_switch_2
          - sensor.hydroponics_state_ultraviolet
          - sensor.hydroponics_state_temperature
          - switch.hydroponics_control_switch
          - sensor.hydroponics_state_relative_humidity
          - switch.hydroponics_control_switch_3
  - title: Rooms
    cards:
      - type: entities
        title: Master Bedroom
        entities:
          - switch.master_bedroom_light_switch
          - light.master_bedroom_reading
      - type: entities
        title: Exterior
        entities:
          - switch.outside_light_switch
      - type: entities
        title: Kitchen
        entities:
          - switch.kitchen_light_switch
          - switch.coffee_switch
          - light.kitchen_sink
      - type: media-control
        entity: media_player.kitchen
      - type: entities
        title: Garage
        entities:
          - cover.garage_door
      - type: entities
        title: Living Room
        entities:
          - light.living_room_side_tables
          - switch.living_room_light_switch
      - type: entities
        title: Basement
        entities:
          - light.basement_light_level
      - type: media-control
        entity: media_player.basement
  - title: Automation
    cards:
      - type: entities
        title: All Automations
        entities:
          - automation.arriving_home
          - automation.sunset
          - automation.hydroponic_light_on
          - automation.arriving_home_after_sunset
          - automation.notifiy__close_garage_door_if_open_at_night
          - automation.trigger_2_hour_coffee_timer
          - automation.hydroponic_light_off
          - automation.hydroponic_fan_off
          - automation.home_assistant_update
          - automation.leaving_home
          - automation.sunrise
          - automation.startup_notification
          - automation.hydroponic_fan_on
      - type: entities
        title: All Scripts
        entities:
          - script.thermostat

