alias: Arriving Home
trigger:
- platform: state
  entity_id: device_tracker.mitchel
  from: 'not_home'
  to: 'home'
- platform: state
  entity_id: device_tracker.renee
  from: 'not_home'
  to: 'home'
action:
- service: climate.ecobee_resume_program
  data:
    entity_id: climate.home
    resume_all: true
