alias: Arriving Home After Sunset
trigger:
- platform: state
  entity_id: device_tracker.mitchel
  from: 'not_home'
  to: 'home'
- platform: state
  entity_id: device_tracker.renee
  from: 'not_home'
  to: 'home'
condition:
  condition: sun
  after: sunset
action:
- service: light.turn_on
  entity_id: light.living_room_ceiling_fan_1
  data:
    brightness: 254
    rgb_color: [255, 199, 116]
- service: light.turn_on
  entity_id: light.living_room_ceiling_fan_2
  data:
    brightness: 254
    rgb_color: [255, 199, 116]
- service: light.turn_on
  entity_id: light.living_room_ceiling_fan_3
  data:
    brightness: 254
    rgb_color: [255, 199, 116]



