alias: Arriving Home
trigger:
- platform: state
  entity_id: group.family
  from: 'not_home'
  to: 'home'
action:
- service: light.turn_on
  entity_id: light.living_room_ceiling_fan_1
  data:
    brightness: 254
    rgb_color: [255, 199, 116]
- service: light.turn_on
  entity_id: light.living_room_ceiling_fan_2
  data:
    brightness: 254
    rgb_color: [255, 199, 116]
- service: light.turn_on
  entity_id: light.living_room_ceiling_fan_3
  data:
    brightness: 254
    rgb_color: [255, 199, 116]



