alias: Arriving Home After Sunset
trigger:
- platform: state
  entity_id: device_tracker.mitchel
  from: 'not_home'
  to: 'home'
- platform: state
  entity_id: device_tracker.renee
  from: 'not_home'
  to: 'home'
condition:
  condition: sun
  after: sunset
action:
- service: switch.turn_on
  entity_id: switch.living_room_light_switch_switch_6_0
