alias: Leaving Home
trigger:
- platform: state
  entity_id: group.family
  from: 'home'
  to: 'not_home'
action:
- service: homeassistant.turn_off
  entity_id: group.home
- service: switch.turn_off
  entity_id: switch.coffee_switch_4_0
- service: homeassistant.turn_off
  entity_id: script.coffee_timer_off
