alias: Turn on living room when sun sets
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: device_tracker.mitchel
    state: 'home'
  - condition: state
    entity_id: device_tracker.renee
    state: 'home'
action:
  service: homeassistant.turn_on
  entity_id: group.living_room
