alias: Home Assistant Update
trigger:
- platform: state
  entity_id: updater.updater

condition:
- condition: template
  value_template: "{{ states('updater.updater') != 'unknown' }}"

action:
- service: notify.ios_mitchs_iphone
  data:
    title: 'New Version of Home-Assistant Available.'
    message: "Version: {{ states('updater.updater') }}"
