alias: Sunset When Home
trigger:
  platform: sun
  event: sunset
  offset: "-00:10:00"
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: device_tracker.mitchel
    state: 'home'
  - condition: state
    entity_id: device_tracker.renee
    state: 'home'
action:
- service: switch.turn_on
  entity_id: switch.living_room_light_switch_switch_6_0
