# Tabs
default_view:
  name: Home
  view: yes
  entities:
  - configurator.philips_hue
  - configurator.ecobee
  - persistent_notification.update_available
  - group.climate
  - group.family
  - group.forecast
  - group.automation

rooms:
  name: Rooms
  view: yes
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.exterior
  - group.basement

# Rooms
home:
  name: Home
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.basement

main_room:
  name: Main Room
  entities:
  - group.kitchen
  - group.living_room

basement:
  name: Basement
  entities:
  - binary_sensor.downstairs_occupancy

living_room:
  name: Living Room
  entities:
  - light.living_room_ceiling_fan_1
  - light.living_room_ceiling_fan_2
  - light.living_room_ceiling_fan_3

kitchen:
  name: Kitchen
  entities:
  - media_player.kitchen
  - switch.kitchen_light_switch_switch_3_0
  - switch.coffee_switch_4_0

master_bedroom:
  name: Master Bedroom
  entities:
  - switch.master_bedroom_light_switch_switch_2_0
  - light.master_bedroom_reading

exterior:
  name: Exterior
  entities:
  - switch.outside_light_switch_switch_5_0

# Lights
lights:
  name: Lights
  entities:
  - group.interior_lights
  - group.exterior_lights

interior_lights:
  name: Interior Lights
  entities:
  - group.living_room_lights
  - group.kitchen_lights
  - group.master_bedroom_lights

exterior_lights:
  name: Exterior Lights
  entities:
  - switch.outside_light_switch_switch_5_0

main_room_lights:
  name: Main Room Lights
  entities:
  - group.kitchen_lights
  - group.living_room_lights

master_bedroom_lights:
  name: Master Bedroom Lights
  entities:
  - switch.master_bedroom_light_switch_switch_2_0
  - light.master_bedroom_reading

kitchen_lights:
  name: Kitchen Lights
  entities:
  - switch.kitchen_light_switch_switch_3_0

living_room_lights:
  name: Living Room Lights
  entities:
  - light.living_room_ceiling_fan_1
  - light.living_room_ceiling_fan_2
  - light.living_room_ceiling_fan_3

# Other
family:
  name: Family
  entities:
  - device_tracker.mitchel
  - device_tracker.renee

climate:
  name: Climate
  entities:
  - climate.home
  - sensor.downstairs_temperature
  - sensor.home_temperature

forecast:
  name: Forecast
  entities:
  - sun.sun
  - sensor.dark_sky_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_daily_high_temperature
  - sensor.dark_sky_daily_low_temperature
  - sensor.dark_sky_precip

automation:
  name: Automation
  entities:
  - automation.arriving_home_after_sunset
  - automation.home_assistant_update
  - automation.turn_off_coffee_after_two_hours
  - automation.leaving_home
  - automation.sunset_when_home
  - automation.sunset
  - automation.sunrise
  - automation.startup_notification
  - automation.login_failure
