# Tabs
default_view:
  name: Home
  view: yes
  entities:
  - configurator.philips_hue
  - configurator.ecobee
  - persistent_notification.update_available
  - group.climate
  - group.family
  - group.forecast
  - group.hydroponics

rooms:
  name: Rooms
  view: yes
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.mitchels_office
  - group.exterior
  - group.basement
  - group.garage

automation:
  name: Automation
  view: yes
  entities:
  - group.all_automations
  - group.all_scripts

# Rooms
home:
  name: Home
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.basement

main_room:
  name: Main Room
  entities:
  - group.kitchen
  - group.living_room

basement:
  name: Basement
  entities:
  - media_player.basement
  - light.basement_light_level

living_room:
  name: Living Room
  entities:
  - switch.living_room_light_switch
  - light.living_room_side_tables

kitchen:
  name: Kitchen
  entities:
  - media_player.kitchen
  - switch.coffee_switch
  - switch.kitchen_light_switch
  - light.kitchen_sink

master_bedroom:
  name: Master Bedroom
  entities:
  - switch.master_bedroom_light_switch
  - light.master_bedroom_reading

mitchels_office:
  name: Mitchel's Office
  entities:
  - light.mitchels_office_reading

garage:
  name: Garage
  entities:
  - cover.garage_door

exterior:
  name: Exterior
  entities:
  - switch.outside_light_switch

# Lights
lights:
  name: Lights
  entities:
  - group.interior_lights
  - group.exterior_lights

interior_lights:
  name: Interior Lights
  entities:
  - group.living_room_lights
  - group.kitchen_lights
  - group.master_bedroom_lights
  - group.mitchels_office_lights

exterior_lights:
  name: Exterior Lights
  entities:
  - switch.outside_light_switch

main_room_lights:
  name: Main Room Lights
  entities:
  - group.kitchen_lights
  - group.living_room_lights

master_bedroom_lights:
  name: Master Bedroom Lights
  entities:
  - switch.master_bedroom_light_switch
  - light.master_bedroom_reading

kitchen_lights:
  name: Kitchen Lights
  entities:
  - light.kitchen_sink
  - switch.kitchen_light_switch_switch

living_room_lights:
  name: Living Room Lights
  entities:
  - light.living_room_side_tables
  - switch.living_room_light_switch

mitchels_office_lights:
  name: Mitchel's Office Lights
  entities:
  - light.mitchels_office_reading
