# Tabs
default_view:
  name: Home
  view: yes
  entities:
  - configurator.philips_hue
  - configurator.ecobee
  - persistent_notification.update_available
  - group.climate
  - group.family
  - group.forecast

rooms:
  name: Rooms
  view: yes
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.exterior
  - group.basement

automation:
  name: Automation
  view: yes
  entities:
  - group.all_automations
  - group.all_scripts

# Rooms
home:
  name: Home
  entities:
  - group.living_room
  - group.kitchen
  - group.master_bedroom
  - group.basement

main_room:
  name: Main Room
  entities:
  - group.kitchen
  - group.living_room

basement:
  name: Basement
  entities:
  - binary_sensor.downstairs_occupancy

living_room:
  name: Living Room
  entities:
  - switch.living_room_light_switch_switch_6_0
  - light.living_room_side_table_left
  - light.living_room_side_table_right

kitchen:
  name: Kitchen
  entities:
  - media_player.kitchen
  - switch.coffee_switch_4_0
  - switch.kitchen_light_switch_switch_3_0
  - light.kitchen_sink_1
  - light.kitchen_sink_2
  - light.kitchen_sink_3

master_bedroom:
  name: Master Bedroom
  entities:
  - switch.master_bedroom_light_switch_switch_2_0
  - light.master_bedroom_reading
  - media_player.bedroom_apple_tv

exterior:
  name: Exterior
  entities:
  - switch.outside_light_switch_switch_5_0

# Lights
lights:
  name: Lights
  entities:
  - group.interior_lights
  - group.exterior_lights

interior_lights:
  name: Interior Lights
  entities:
  - group.living_room_lights
  - group.kitchen_lights
  - group.master_bedroom_lights

exterior_lights:
  name: Exterior Lights
  entities:
  - switch.outside_light_switch_switch_5_0

main_room_lights:
  name: Main Room Lights
  entities:
  - group.kitchen_lights
  - group.living_room_lights

master_bedroom_lights:
  name: Master Bedroom Lights
  entities:
  - switch.master_bedroom_light_switch_switch_2_0
  - light.master_bedroom_reading

kitchen_lights:
  name: Kitchen Lights
  entities:
  - group.kitchen_sink
  - switch.kitchen_light_switch_switch_3_0

kitchen_sink:
  name: Kitchen Sink
  entities:
  - light.kitchen_sink_1
  - light.kitchen_sink_2
  - light.kitchen_sink_3

living_room_lights:
  name: Living Room Lights
  entities:
  - group.living_room_side_tables
  - switch.living_room_light_switch_switch_6_0

living_room_side_tables:
  name: Living Room Side Tables
  entities:
  - light.living_room_side_table_left
  - light.living_room_side_table_right

# Other
family:
  name: Family
  entities:
  - device_tracker.mitchel
  - device_tracker.renee

climate:
  name: Climate
  entities:
  - climate.home
  - sensor.downstairs_temperature
  - sensor.home_temperature

forecast:
  name: Forecast
  entities:
  - sun.sun
  - sensor.dark_sky_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_daily_high_temperature
  - sensor.dark_sky_daily_low_temperature
  - sensor.dark_sky_precip
