- platform: smtp
  name: mp_email
  server: smtp.gmail.com
  port: 587
  sender: !secret mitchel_email
  username: !secret mitchel_email
  password: !secret mitchel_email_password
  recipient: !secret mitchel_email
  starttls: true

- platform: smtp
  name: rp_email       
  server: smtp.gmail.com
  port: 587
  sender: !secret mitchel_email
  username: !secret mitchel_email
  password: !secret mitchel_email_password
  recipient: !secret renee_email
  starttls: true

- platform: group
  name: notify_mitchel
  services:
    - service: ios_mitchs_iphone

- platform: group
  name: notify_renee
  services:
    - service: ios_renees_iphone

- platform: group
  name: notify_all
  services:
    - service: notify_mitchel
    - service: notify_renee
